### ISSUE TITLE
NameError: global name 'args' is not defined

### ISSUE THREAD

**Issue by gopinath6** [RUB-NDS/CORStest#1]
Am getting below error, can you please help to resolve?
OS:Win 7

Traceback (most recent call last):
  File "C:\Users\kandasam\CORStest\corstest.py", line 112, in <module>
    main()
  File "C:\Users\kandasam\CORStest\corstest.py", line 31, in main
    try: pool.map_async(check, urls).get(2**32)
  File "C:\Users\kandasam\.windows-build-tools\python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
NameError: global name 'args' is not defined

![cors test error](https://user-images.githubusercontent.com/6551119/27872732-5dd1b2ac-61c7-11e7-9166-14511eef5602.JPG)

**Comment by svlada** [comment]
I'm getting the same exception

**Comment by gopinath6** [comment]
Any idea how to fix?
